import{a as w,i as n,S}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();async function p(e,o){const s="51719730-f0601b97791df742fe437894d",a="https://pixabay.com/api/",t={key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await w.get(a,{params:t})).data}catch(r){return n.error({title:"Error",message:`Не вдалося отримати зображення: ${r.message}`,position:"topRight",timeout:5e3}),{hits:[],totalHits:0}}}const h=document.querySelector(".gallery"),v=new S(".gallery a");function q(e){return`
    <a href="${e.largeImageURL}" class="gallery__item">
      <img src="${e.webformatURL}" alt="${e.tags}" />
      <div class="stats">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </a>
  `}function y(e){const o=e.map(q).join("");h.insertAdjacentHTML("beforeend",o),v.refresh()}function E(){h.innerHTML=""}function g(){document.querySelector(".loader").classList.add("visible")}function L(){document.querySelector(".loader").classList.remove("visible")}function B(){document.querySelector(".js-loadbtn").classList.remove("is-hidden")}function b(){document.querySelector(".js-loadbtn").classList.add("is-hidden")}function C(e){e.disabled=!0,e.classList.add("is-disabled")}function m(e){e.disabled=!1,e.classList.remove("is-disabled")}const P=document.querySelector(".form"),_=document.querySelector(".form-input"),l=document.querySelector(".js-loadbtn");let u="",c=1,i=0,f=0;P.addEventListener("submit",async e=>{e.preventDefault();const o=_.value.trim();if(!o){n.info({title:"Info",message:"Please enter a search query!",position:"topCenter"});return}u=o,c=1,i=0,E(),b(),g();try{const s=await p(u,c);if(f=s.totalHits,s.hits.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}y(s.hits),i+=s.hits.length,$()&&B()}catch(s){n.error({title:"Error",message:"Something went wrong. Try again later.",position:"topCenter"}),console.error("Fetch error:",s)}finally{L()}});l.addEventListener("click",async()=>{c+=1,C(l),g();try{const e=await p(u,c);y(e.hits),i+=e.hits.length,i>=f?(b(),n.info({title:"End of Results",message:"You've reached the end of search results.",position:"topCenter"})):m(l),R()}catch(e){n.error({title:"Error",message:"Failed to load more images.",position:"topCenter"}),console.error("Load more error:",e),m(l)}finally{L()}});function $(){return i<f}function R(){const e=document.querySelector(".gallery__item");if(!e)return;const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
